// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Noël Danjou

using System.Text;
using System.Text.Encodings.Web;
using System.Text.Json;
using System.Xml.Linq;
using Microsoft.Extensions.Configuration;
using TagInfoGen;

const string SettingsFileName = "appsettings.json";
const string DefaultPresetRelativePath = "presets/French_Railway_Signalling.xml";
const string DefaultOutputFileName = "taginfo.json";

// Resolve the repository root (nearest parent containing a .git folder) so the
// tool can be launched from anywhere in the repository, including a tools/
// subfolder under GitHub Actions. Falls back to the current directory.
var repositoryRoot = FindRepositoryRoot(Directory.GetCurrentDirectory());

var inputPath = args.Length > 0
    ? args[0]
    : Path.Combine(repositoryRoot, DefaultPresetRelativePath);

var outputPath = args.Length > 1
    ? args[1]
    : Path.Combine(repositoryRoot, DefaultOutputFileName);

// The log defaults to taginfo.md next to the output, but a third argument can
// place it elsewhere (for example to keep it out of the deployed Pages folder).
var logPath = args.Length > 2
    ? args[2]
    : Path.ChangeExtension(outputPath, ".md");

if (!File.Exists(inputPath))
{
    Console.Error.WriteLine($"Error: input file '{inputPath}' not found.");
    return 1;
}

try
{
    var configuration = LoadConfiguration();
    var settings = configuration.GetSection("Project").Get<ProjectSettings>();
    if (settings == null)
    {
        Console.Error.WriteLine($"Error: missing 'Project' section in {SettingsFileName}.");
        return 1;
    }

    Console.WriteLine($"Reading presets from '{inputPath}'...");
    var document = XDocument.Load(inputPath);

    var parser = new PresetParser(
        document,
        settings.PresetUrl,
        settings.UseFrenchDescriptions,
        settings.ExcludedKeys);
    var tags = parser.Parse(document);

    var taginfo = new TagInfoFile
    {
        DataUrl = settings.DataUrl,
        Project = new TagInfoProject
        {
            Name = settings.Name,
            Description = settings.Description,
            ProjectUrl = settings.ProjectUrl,
            DocUrl = settings.DocUrl,
            IconUrl = IconResolver.Resolve(settings.PresetUrl, settings.IconPath),
            ContactName = settings.ContactName,
            ContactEmail = settings.ContactEmail,
        },
        Tags = tags,
    };

    var options = new JsonSerializerOptions // CA1869
    {
        WriteIndented = true,
        // Keep accented characters and URLs readable instead of \u escaped.
        Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
        DefaultIgnoreCondition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull,
    };

    var utf8NoBom = new UTF8Encoding(false);
    File.WriteAllText(outputPath, JsonSerializer.Serialize(taginfo, options), utf8NoBom);

    var withIcon = tags.Count(t => t.IconUrl is not null);
    var presetVersion = document.Root?.Attribute("version")?.Value ?? "unknown";
    File.WriteAllText(logPath, BuildLog(presetVersion, inputPath, outputPath, settings, tags.Count, withIcon), utf8NoBom);

    Console.WriteLine($"Wrote '{outputPath}': {tags.Count} tag entries ({withIcon} with an icon).");
    Console.WriteLine($"Wrote '{logPath}'.");
    return 0;
}
catch (Exception ex)
{
    Console.Error.WriteLine($"Error: generation failed - {ex.Message}");
    return 1;
}

static IConfiguration LoadConfiguration()
{
    return new ConfigurationBuilder()
        .SetBasePath(AppContext.BaseDirectory)
        .AddJsonFile(SettingsFileName, optional: false)
        .Build();
}

static string FindRepositoryRoot(string startDirectory)
{
    DirectoryInfo? current = new(startDirectory);

    while (current != null)
    {
        if (Directory.Exists(Path.Combine(current.FullName, ".git")))
        {
            return current.FullName;
        }

        current = current.Parent;
    }

    return startDirectory;
}

static string BuildLog(
    string presetVersion,
    string inputPath,
    string outputPath,
    ProjectSettings settings,
    int tagCount,
    int iconCount)
{
    var language = settings.UseFrenchDescriptions ? "French" : "English";

    return $"""
        # Taginfo project file

        Generated by TagInfoGen from the JOSM presets. Do not edit by hand.

        - Generated (UTC): {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss}
        - Preset version: {presetVersion}
        - Preset file: {Path.GetFileName(inputPath)}
        - Output file: {Path.GetFileName(outputPath)}
        - Description language: {language}
        - Total tag entries: {tagCount}
        - Entries with an icon: {iconCount}

        See https://wiki.openstreetmap.org/wiki/Taginfo/Projects for the format.

        """;
}
