<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <InvariantGlobalization>true</InvariantGlobalization>
    <RootNamespace>Signalling.Sync</RootNamespace>
    <AssemblyName>Signalling.Sync</AssemblyName>
    <Product>Signalling.Sync</Product>
    <Version>1.0.0</Version>
    <Company>Noël Danjou</Company>
    <Authors>Noël Danjou</Authors>
    <Copyright>Copyright (C) 2026 Noël Danjou</Copyright>
    <Description>Comparator that checks synchronization between preset and map tag rules.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Signalling.Core\Signalling.Core.csproj" />
  </ItemGroup>

</Project>
